export const productMenus: { [key: string]: any } = {
  MAN: {
    CLOTHES: ['JUMPER', 'T_SHIRT', 'SHIRTS', 'PANTS', 'COATS', 'JACKET', 'SUIT', 'UNIFORM'],
    SHOES: ['SPORTS_SHOES', 'CASUAL_SHOE', 'WALKING_SHOE', 'SPIKES', 'CLASSICAL', 'OUTDOOR'],
    ACCESSORY: ['GOGGLES', 'WATCH', 'WALLET', 'BAG', 'HATS'],
    ELECTRONIC: ['SHAVER'],
  },
  WOMAN: {
    CLOTHES: ['JUMPER', 'T_SHIRT', 'SHIRTS', 'PANTS', 'COATS', 'JACKET', 'SUIT', 'UNIFORM'],
    SHOES: ['SPORTS_SHOES', 'CASUAL_SHOE', 'WALKING_SHOE', 'SPIKES', 'CLASSICAL', 'OUTDOOR'],
    ACCESSORY: ['GOGGLES', 'WATCH', 'WALLET', 'BAG', 'HATS'],
  },
  CHILD: {
    CLOTHES: ['JUMPER', 'T_SHIRT', 'SHIRTS', 'PANTS', 'COATS', 'JACKET', 'SUIT', 'UNIFORM'],
    SHOES: ['SPORTS_SHOES', 'CASUAL_SHOE', 'WALKING_SHOE', 'SPIKES', 'CLASSICAL', 'OUTDOOR'],
    ACCESSORY: ['GOGGLES', 'WATCH', 'BAG', 'HATS'],
  },
  PET: {
    CAT: ['DRY_FOOD', 'WET_FOOD', 'VITAMIN', 'BALL', 'SCRATCHING_POST', 'CARE', 'CAT_LITTER'],
    DOG: ['DRY_FOOD', 'WET_FOOD', 'VITAMIN', 'BALL', 'CARE', 'DOG_COLLAR', 'DOG_TOILET'],
    BIRD: ['FOOD', 'CARE', 'CAGE', 'LUNCH_BOX', 'WATER_BOX'],
  },
  ELECTRONIC: {
    WHITE_APPLIANCES: ['ICEBOX', 'WASHING_MACHINE', 'DISHWASHER', 'STOVE'],
    KITCHEN: ['KETTLE', 'COFFEE_MAKER', 'SANDWICH_MAKER', 'MIKSER', 'WEIGHT'],
    OTHER: ['TV', 'VACUUM_CLEANER', 'ELECTRIC_TOOTHBRUSH', 'EARPHONE', 'SPEAKER'],
  },
  SPORT: {
    SPORTSWEAR: ['SPORTS_T_SHIRT', 'SPORTS_SHORTS', 'TRACKSUIT', 'SPORTS_SWEATSHIRT'],
    GYM_SHOE: ['RUNNING_SHOES', 'ASTROTURF_SHOES', 'BASKETBALL_SHOES', 'WALKING_SHOE', 'OUTDOOR_SHOES', 'OUTDOOR_BOT'],
    SPORTS_EQUIPMENT: [
      'SKATEBOARD',
      'CAMPING_TOOLS',
      'MOUNTAINEERING_CLIMBING',
      'TENT',
      'FISHING_SUPPLIES',
      'DUMBBELL',
    ],
    SPORTS_NUTRITION: ['PROTEIN_POWDER', 'AMINO_ACIDS', 'CARBOHYDRATE', 'CREATINE'],
  },
};
