export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_MAIN_CATEGORY_PRODUCTS = 'SET_MAIN_CATEGORY_PRODUCTS';
export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
export const SET_SUB_CATEGORY_PRODUCTS = 'SET_SUB_CATEGORY_PRODUCTS';
export const SET_SIMILAR_PRODUCT_PRODUCTS = 'SET_SIMILAR_PRODUCT_PRODUCTS';
